artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/wafers.csv

data validation:
  root_dir: artifacts/data_validation
  file_dir: artifacts/data_ingestion/wafers.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/wafers.csv
  preprocessor_name: preprocessor.joblib

model_trainer:
  root_dir: artifacts/model_trainer
  x_train_data_path: artifacts/data_transformation/X_train.npy
  y_train_data_path: artifacts/data_transformation/y_train.npy
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  x_test_data_path: artifacts/data_transformation/X_test.npy
  y_test_data_path: artifacts/data_transformation/y_test.npy
  model_path: artifacts/model_trainer/model.joblib
  metrics_name: metrics.json